[package]
name = "mentoriabot_forms"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
poise = "0.5.2"
tokio = { version = "1.25.0", features = ["full"] }
async-trait = "0.1.64"
mentoriabot_macros = { path = "../macros" }
