[package]
name = "minirustbot_forms"
version = "0.1.0"
authors = ["PgBiel"]
edition = "2021"
license = "MIT"


[dependencies]
poise = "0.5.2"
tokio = { version = "1.25.0", features = ["full"] }
async-trait = "0.1.64"
minirustbot_macros = { path = "../macros" }
